backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

site_url: https://mjosolutions.netlify.app/
display_url: https://mjosolutions.netlify.app/
logo_url: https://mjosolutions.netlify.app/MJO_IconLogo.jpg

media_folder: static/img
public_folder: /img

collections:
  - label: "About Page"
    name: "about"
    files:
      - label: "Intro"
        name: "intro"
        file: "/content/pages/about/intro.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Header, name: header, widget: string }
          - { label: Intro1, name: intro1, widget: string }
          - { label: Intro2, name: intro2, widget: string }
      - label: "Solutions"
        name: "solutions"
        file: "/content/pages/about/solutions.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Header, name: header, widget: string }
          - { label: Sol1, name: sol1, widget: string }
          - { label: Sol2, name: sol2, widget: string }
          - { label: Sol3, name: sol3, widget: string }
          - { label: Sol4, name: sol4, widget: string }
          - { label: Sol5, name: sol5, widget: string }
      - label: "What"
        name: "what"
        file: "/content/pages/about/what.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Header, name: header, widget: string }
          - { label: Body, name: body, widget: markdown }
      - label: "Why"
        name: "why"
        file: "/content/pages/about/why.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Header, name: header, widget: string }
          - { label: Why1, name: why1, widget: string }
          - { label: Why2, name: why2, widget: string }
          - { label: Why3, name: why3, widget: string }
          - { label: Why4, name: why4, widget: string }
          - { label: Why5, name: why5, widget: string }
      - label: "Where"
        name: "where"
        file: "/content/pages/about/where.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Header, name: header, widget: string }
          - { label: Body, name: body, widget: markdown }
