backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

site_url: https://mjosolutions.netlify.app/
display_url: https://mjosolutions.netlify.app/
logo_url: https://mjosolutions.netlify.app/MJO_IconLogo.jpg

media_folder: static/img
public_folder: /img

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "About Page"
        name: "about"
        file: "/content/pages/about.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
          - { label: Solutions, name: solutions, widget: markdown }
          - { label: What, name: what, widget: markdown }
          - { label: Why, name: why, widget: markdown }
          - { label: Where, name: where, widget: markdown }
          - { label: Contact, name: contact, widget: markdown }
