backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

site_url: https://mjosolutions.netlify.app/
display_url: https://mjosolutions.netlify.app/
logo_url: https://mjosolutions.netlify.app/MJO_IconLogo.jpg

media_folder: static/img
public_folder: /img

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Intro"
        name: "intro"
        file: "/content/pages/about/intro.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Header, name: header, widget: string }
          - { label: Body, name: body, widget: markdown }
      - label: "What"
        name: "what"
        file: "/content/pages/about/what.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Header, name: header, widget: string }
          - { label: Body, name: body, widget: markdown }
